"""Ask the Data — controlled text-to-SQL over the marts (SELECT-only guard)."""

from __future__ import annotations

import streamlit as st
from streamlit_app import ui
from streamlit_app.agent import build_sql
from streamlit_app.db import require_marts, run_df

from jmi_core.settings import get_settings
from jmi_enrichment.providers import get_provider

st.set_page_config(page_title="Ask the Data", page_icon="💬", layout="wide")
st.title("💬 Ask the Data")
st.caption("Natural-language questions → **read-only** SQL over the marts, generated by the LLM.")

require_marts(
    "marts.FT_JOB_POSTING",
    missing="Connected, but no marts yet — run the pipeline, then `make dbt-build`.",
)

settings = get_settings()
st.caption(f"Provider `{settings.llm_provider}` · model `{settings.llm_model}`")

examples = [
    "Which recognised-sponsor companies in NL have the most open roles?",
    "How many postings are there per country?",
    "Top 10 technologies across all postings",
    "Companies hiring Data Engineers where English is sufficient",
]

if "ask_q" not in st.session_state:
    st.session_state.ask_q = examples[0]

st.write("**Try one:**")
cols = st.columns(2)
for i, ex in enumerate(examples):
    if cols[i % 2].button(ex, width="stretch"):
        st.session_state.ask_q = ex

question = st.text_input("Your question", key="ask_q")
go = st.button("Ask", type="primary")

if go and question.strip():
    with st.spinner("Generating SQL…"):
        try:
            sql = build_sql(question, get_provider(settings))
        except Exception as exc:
            st.error(f"Could not generate a safe query: {exc}")
            st.stop()

    st.code(sql, language="sql")
    with st.spinner("Running query…"):
        try:
            df = run_df(sql)
        except Exception as exc:
            st.error(f"Query failed: {exc}")
            st.stop()

    st.success(f"{len(df):,} rows")

    # Auto-chart a clean 2-column (label, measure) result.
    numeric = df.select_dtypes("number")
    if df.shape[1] == 2 and numeric.shape[1] == 1 and 1 <= len(df) <= 30:
        label = next(c for c in df.columns if c not in numeric.columns)
        value = numeric.columns[0]
        ui.show(ui.hbar(df, label, value, value_title=value.replace("_", " ")))
    ui.table(df)
